### ISSUE TITLE
how integrate in our admin panel

### ISSUE THREAD

**Issue by singhsandeepsln** [pazznetwork/ngx-chat#10]
how integrate in our admin panel
Angular CLI: 1.7.4
Node: 10.16.0
OS: linux x64
Angular: 5.2.11

**Comment by singhsandeepsln** [comment]
WARNING in ./node_modules/@angular/cdk/esm5/platform.es5.js
102:50-68 "export 'ɵɵdefineInjectable' was not found in '@angular/core'

**Comment by singhsandeepsln** [comment]
getting error 
Socket.js:4 Uncaught ReferenceError: global is not defined
    at Object../node_modules/@xmpp/plugins/websocket/lib/Socket.js (Socket.js:4)
    at __webpack_require__ (bootstrap:76)
    at Object../node_modules/@xmpp/plugins/websocket/lib/Connection.js (Connection.js:3)
    at __webpack_require__ (bootstrap:76)
    at Object../node_modules/@xmpp/plugins/websocket/index.js (index.js:3)
    at __webpack_require__ (bootstrap:76)
    at Object../node_modules/@pazznetwork/ngx-chat/fesm5/pazznetwork-ngx-chat.js (pazznetwork-ngx-chat.js:1)
    at __webpack_require__ (bootstrap:76)
    at Object../src/app/app.component.ts (main.js:9906)
    at __webpack_require__ (bootstrap:76)
./node_modules/@xmpp/plugins/websocket/lib/Socket.js @ Socket.js:4
__webpack_require__ @ bootstrap:76
./node_modules/@xmpp/plugins/websocket/lib/Connection.js @ Connection.js:3
__webpack_require__ @ bootstrap:76
./node_modules/@xmpp/plugins/websocket/index.js @ index.js:3
__webpack_require__ @ bootstrap:76
./node_modules/@pazznetwork/ngx-chat/fesm5/pazznetwork-ngx-chat.js @ pazznetwork-ngx-chat.js:1
__webpack_require__ @ bootstrap:76
./src/app/app.component.ts @ main.js:9906
__webpack_require__ @ bootstrap:76
./src/app/app.module.ts @ app.component.ts:26
__webpack_require__ @ bootstrap:76
./src/main.ts @ main.ts:1
__webpack_require__ @ bootstrap:76
5 @ main.js:10216
__webpack_require__ @ bootstrap:76
checkDeferredModules @ bootstrap:43
(anonymous) @ bootstrap:134
(anonymous) @ bootstrap:134
client?e0b3:52

**Comment by trampi** [comment]
Hi @singhsandeepsln,

We do not support Angular 5.

As said in the requirements, you have to use Angular 6, support for Angular 8 is coming in the next days. We will skip Angular 7.

Do not hesitate to ask again or reopen the ticket if you have further questions!

**Comment by singhsandeepsln** [comment]
getting error

Uncaught TypeError: Object(...) is not a function
    at platform.es5.js:102
    at Object../node_modules/@angular/cdk/esm5/platform.es5.js (platform.es5.js:104)
    at __webpack_require__ (bootstrap:76)
    at Object../node_modules/@angular/cdk/esm5/text-field.es5.js (text-field.es5.js:1)
    at __webpack_require__ (bootstrap:76)
    at Object../node_modules/@pazznetwork/ngx-chat/fesm5/pazznetwork-ngx-chat.js (pazznetwork-ngx-chat.js:1)
    at __webpack_require__ (bootstrap:76)
    at Object../src/app/app.component.ts (main.js:9906)
    at __webpack_require__ (bootstrap:76)
    at Object../src/app/app.module.ts (app.component.ts:26)
(anonymous) @ platform.es5.js:102
./node_modules/@angular/cdk/esm5/platform.es5.js @ platform.es5.js:104
__webpack_require__ @ bootstrap:76
./node_modules/@angular/cdk/esm5/text-field.es5.js @ text-field.es5.js:1
__webpack_require__ @ bootstrap:76
./node_modules/@pazznetwork/ngx-chat/fesm5/pazznetwork-ngx-chat.js @ pazznetwork-ngx-chat.js:1
__webpack_require__ @ bootstrap:76
./src/app/app.component.ts @ main.js:9906
__webpack_require__ @ bootstrap:76
./src/app/app.module.ts @ app.component.ts:26
__webpack_require__ @ bootstrap:76
./src/main.ts @ main.ts:1
__webpack_require__ @ bootstrap:76
5 @ main.js:10216
__webpack_require__ @ bootstrap:76
checkDeferredModules @ bootstrap:43
(anonymous) @ bootstrap:134
(anonymous) @ bootstrap:134
client?e0b3:52 [WDS] Live Reloading enabled.
client?e0b3:126 [WDS] Warnings while compiling.
warnings @ client?e0b3:126
(anonymous) @ socket.js:40
sock.onmessage @ SockJSClient.js:58
EventTarget.dispatchEvent @ sockjs.js:170
(anonymous) @ sockjs.js:887
SockJS._transportMessage @ sockjs.js:885
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2961
wrapFn @ zone.js:1332
./node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:423
./node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:195
./node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:498
invokeTask @ zone.js:1744
globalZoneAwareCallback @ zone.js:1770
client?e0b3:135 ./node_modules/@angular/cdk/esm5/platform.es5.js
102:130-138 "export 'ɵɵinject' was not found in '@angular/core'
warnings @ client?e0b3:135
(anonymous) @ socket.js:40
sock.onmessage @ SockJSClient.js:58
EventTarget.dispatchEvent @ sockjs.js:170
(anonymous) @ sockjs.js:887
SockJS._transportMessage @ sockjs.js:885
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2961
wrapFn @ zone.js:1332
./node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:423
./node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:195
./node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:498
invokeTask @ zone.js:1744
globalZoneAwareCallback @ zone.js:1770



Angular CLI: 6.0.8
Node: 10.16.0
OS: linux x64
Angular: 6.1.10

**Comment by trampi** [comment]
Please provide the output of `ng -v`.
Could you upload a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. in a repository on GitHub?

**Comment by singhsandeepsln** [comment]
Angular CLI: 6.0.8
Node: 10.16.0
OS: linux x64
Angular: 6.1.10

**Comment by singhsandeepsln** [comment]
I have simply created new project using `ng new chat` and followed installation instruction given in your repository

**Comment by trampi** [comment]
Please add the following to the bottom of your polyfills.ts:
```
/***************************************************************************************************
 * APPLICATION IMPORTS
 */
(window as any).global = window;
```

**Comment by singhsandeepsln** [comment]
> Please add the following to the bottom of your polyfills.ts:
> 
> ```
> /***************************************************************************************************
>  * APPLICATION IMPORTS
>  */
> (window as any).global = window;
> ```

after adding i am getting error in web console
Uncaught TypeError: Object(...) is not a function
    at platform.es5.js:102
    at Object../node_modules/@angular/cdk/esm5/platform.es5.js (platform.es5.js:104)
    at __webpack_require__ (bootstrap:76)
    at Object../node_modules/@angular/cdk/esm5/text-field.es5.js (text-field.es5.js:1)
    at __webpack_require__ (bootstrap:76)
    at Object../node_modules/@pazznetwork/ngx-chat/fesm5/pazznetwork-ngx-chat.js (pazznetwork-ngx-chat.js:1)
    at __webpack_require__ (bootstrap:76)
    at Object../src/app/app.component.ts (main.js:9906)
    at __webpack_require__ (bootstrap:76)
    at Object../src/app/app.module.ts (app.component.ts:26)
(anonymous) @ platform.es5.js:102
./node_modules/@angular/cdk/esm5/platform.es5.js @ platform.es5.js:104
__webpack_require__ @ bootstrap:76
./node_modules/@angular/cdk/esm5/text-field.es5.js @ text-field.es5.js:1
__webpack_require__ @ bootstrap:76
./node_modules/@pazznetwork/ngx-chat/fesm5/pazznetwork-ngx-chat.js @ pazznetwork-ngx-chat.js:1
__webpack_require__ @ bootstrap:76
./src/app/app.component.ts @ main.js:9906
__webpack_require__ @ bootstrap:76
./src/app/app.module.ts @ app.component.ts:26
__webpack_require__ @ bootstrap:76
./src/main.ts @ main.ts:1
__webpack_require__ @ bootstrap:76
5 @ main.js:10216
__webpack_require__ @ bootstrap:76
checkDeferredModules @ bootstrap:43
(anonymous) @ bootstrap:134
(anonymous) @ bootstrap:134
client:52 [WDS] Live Reloading enabled.
client:126 [WDS] Warnings while compiling.
warnings @ client:126
(anonymous) @ socket.js:40
sock.onmessage @ SockJSClient.js:58
EventTarget.dispatchEvent @ sockjs.js:170
(anonymous) @ sockjs.js:887
SockJS._transportMessage @ sockjs.js:885
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2961
wrapFn @ zone.js:1332
./node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:423
./node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:195
./node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:498
invokeTask @ zone.js:1744
globalZoneAwareCallback @ zone.js:1770
client:135 ./node_modules/@angular/cdk/esm5/platform.es5.js
102:130-138 "export 'ɵɵinject' was not found in '@angular/core'`
`

**Comment by trampi** [comment]
I created a fresh angular 6 sample app for you.
https://github.com/trampi/ngx-chat-angular6

By the way, please post the complete output of `ng -v`, because I looks like you might have a dependency problem. It should look like this:
```
Angular CLI: 6.0.8
Node: 10.15.1
OS: darwin x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cdk                      6.0.2
@angular/cli                      6.0.8
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.0.0
typescript                        2.7.2
webpack                           4.8.3
```

Have you tried to `rm -rf node_modules` and reinstall your dependencies?

**Comment by singhsandeepsln** [comment]
please check the complete output of ng -v
`Angular CLI: 1.7.4
Node: 10.16.0
OS: linux x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/cli: 1.7.4
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.7.2
webpack: 3.11.0`

**Comment by trampi** [comment]
please run `ng -v` in your project directory. You are missing @angular/cdk.
