### ISSUE TITLE
Inherit BlockPlugin

### ISSUE THREAD

**Issue by juergen83** [pazznetwork/ngx-chat#100]
Hello,
I tried to extend the BlockPlugin to append custom methods to it but it not works. Here my code:

`export class ContactBlockPlugin extends BlockPlugin {

    public blockedContacts$: BehaviorSubject<boolean>[] = [];
    private blockPlugin: BlockPlugin;

    constructor(
        private chatAdapter: XmppChatAdapter,
        private serviceDiscPlugin: ServiceDiscoveryPlugin,
    ) {
        super(chatAdapter, serviceDiscPlugin);
    }
...
}
`

After compilation Angular show the folling error message:
`
Error: plugin not found: class ContactBlockPlugin extends _pazznetwork_ngx_chat__WEBPACK_IMPORTED_MODULE_1__.BlockPlugin...
`

Do you have a suggestion for me?

BR

**Comment by CodeBast4rd** [comment]
In current Architecture Plugins have to be added to the Plugin List as far as I know.
