### ISSUE TITLE
Unread counter not triggers for new room

### ISSUE THREAD

**Issue by juergen83** [pazznetwork/ngx-chat#116]
Hello guys,

I have troubles to use the build-in solution for unread message counter in rooms. This module works only if rooms are loaded after page refresh but if an other public room is subscribed/ created the trigger for unread counter doesn't work (maybe in background). Only if the page refreshes the number of unreads is visible.

For info: I open or close a room every room change, leave, destroy and subscription:
`this.chatMessageListRegistry.incrementOpenWindowCount(recipient);`
`this.chatMessageListRegistry.decrementOpenWindowCount(recipient);`

Do anyone have an idea?

**Comment by michalgrzegorczyk-dev** [comment]
Hey @juergen83, did you fix this issue? I encountered into a similar problem :/
