### ISSUE TITLE
How to parse custom stanza.

### ISSUE THREAD

**Issue by Vida-Subhash** [pazznetwork/ngx-chat#117]
Unable to parse custom stanza. 
Here's is  eg. Of custom Stanza.
Please find below attached screenshot.
![Screenshot_2022-03-16-23-18-09-04_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/56436741/158654890-0c76e1eb-2d05-4a57-ac77-f1683cb7dc68.jpg)

**Comment by CodeBast4rd** [comment]
Usage of custom stanzas need custom plugins.
