### ISSUE TITLE
Is it possible to view in real time list of all users which have joined selected room?

### ISSUE THREAD

**Issue by jameskentTX** [pazznetwork/ngx-chat#12]
Hi Trampi!
Is it possible to view in real time list of all users which have joined selected room? And see their status.
In a way similar to Roster for Contacts: on the right side of screen, in a window which we can show/hide?

**Comment by trampi** [comment]
Hi @jameskentTX,
at the moment, this is not implemented.
It's possible, though.

### Technical details
After joining a room, we get log messages about stanzas like this:
```
ChatService: unknown stanza <= 
<presence xmlns="jabber:client" xml:lang="en" to="fbeiertrampuschtest@jabber.pazz.de/22464"
 from="test@conference.jabber.pazz.de/fbeiertrampuschtest2">
    <x xmlns="http://jabber.org/protocol/muc#user">
        <item role="participant" affiliation="none"/>
    </x>
</presence>
```

These stanzas contain the information about who is in which room.
The moment a new user joins the room, we also get the stanza above.

If a user in the channel leaves, we get the following stanza:
```
ChatService: unknown stanza <=
 <presence xmlns="jabber:client" to="fbeiertrampuschtest@jabber.pazz.de/22464"
    from="test@conference.jabber.pazz.de/fbeiertrampuschtest2" type="unavailable">
    <x xmlns="http://jabber.org/protocol/muc#user">
        <item role="none" affiliation="none"/>
     </x>
</presence>
```

It shouldn't be too hard to implement user room state tracking. You would have to take a look at `MultiUserChatPlugin#handleStanza` and add a handler for the stanzas mentioned above and  track of the user in the room (see `rooms$`-field). We would have to add a `Occupant`-Array to the room.

If you want, you could try to implement it and create a pull request?

**Comment by jameskentTX** [comment]
My programming is very basic and rude, I really can't add my bad code to your app. It's not a good idea, but thank you for proposition.
