### ISSUE TITLE
Unread message badge issue

### ISSUE THREAD

**Issue by Ahmet-KG** [pazznetwork/ngx-chat#126]
The unread message badge does not disappear when you view the new incoming messages.

**Comment by CodeBast4rd** [comment]
The unread messages count was derived by a custom logic on top of the pub sub protocol. This lead to inconsistent behaviour and a possible edge case error creating too many pub-subs.

We plan a cleaner implementation following the XEP-0085, XEP-0184 and XEP-0333.
