### ISSUE TITLE
(contacts | async).length throws error

### ISSUE THREAD

**Issue by jameskentTX** [pazznetwork/ngx-chat#13]
Hello Trumpi!
Fresh git clone, npm install, change in ngx-chat-imports.ts to development:
`export * from '../../projects/pazznetwork/ngx-chat/src/public_api';`

If you run app (npm start) and log in, `(contacts | async).length` throws error

This error disappears if you change line 12 in roster-list.component.html to:
'<ng-container *ngIf="(contacts | async)**?**.length > 0">'

**Comment by trampi** [comment]
Do you have the latest commit checked out? Do you have any changes? Couldn't reproduce it here. Are you perhabs using 'Toggle contact list'?

**Comment by jameskentTX** [comment]
Yes, I used latest commit. This error appears in development mode only.
`RosterListComponent.html:3 ERROR TypeError: Cannot read property 'length' of null
    at Object.eval [as updateDirectives] (RosterListComponent.html:12)`
Forget it, if you can't reproduce, it's small thing.
