### ISSUE TITLE
Missing Sending status

### ISSUE THREAD

**Issue by minik01** [pazznetwork/ngx-chat#145]
How to reproduce error:

1. Log-in to the chat
2. Open conversation with any roster
3. Block internet connection (for example using devtools)
4. Send message

Actual: _instantly added ✓indicator_
Excepted: _no ✓ indicator (until the connection is re-established)_

**Comment by CodeBast4rd** [comment]
Thank you for the issue and MR will take care of it this week.

**Comment by CodeBast4rd** [comment]
The unread messages count was derived by a custom logic on top of the pub sub protocol. This lead to inconsistent behaviour and a possible edge case error creating too many pub-subs.

We plan a cleaner implementation following the XEP-0085, XEP-0184 and XEP-0333.
