### ISSUE TITLE
How to use multi-user room implementation?

### ISSUE THREAD

**Issue by alexdabast** [pazznetwork/ngx-chat#151]
Hi,

thank you for your work on this implmentation.

I'm using your service only and not your ui-components but I can not find any method to create room or send invitations.

Am I missing something on the implementation ?

Merry xmas

**Comment by SvenBudak** [comment]
any updates here?

**Comment by juergen83** [comment]
Sorry, but I dont know, what you mean exactly. The MUC plugin (MultiUserChatPlugin)  has public methods to create and send invitations to users.

**Comment by SvenBudak** [comment]
It seems that @alexdabast have solved this already. Ticked can be closed.
