### ISSUE TITLE
how to integrate it in IONIC app

### ISSUE THREAD

**Issue by fawadmoon** [pazznetwork/ngx-chat#152]
I tested the app with angular after installation and ng server , it works pretty well in web browser, but I need to integrate it for IONIC app, I am not very expert with IONIC , if I can get some guide line about integrating it with in IONIC app it would be great.

**Comment by CodeBast4rd** [comment]
I am sorry but we can not provide support for custom environment at the current time. If you want to negotiate a payed contract for the support please contact info@pazz.de.
