### ISSUE TITLE
Login throw error when `contact` input in `ChatMessageListComponent` is undefined

### ISSUE THREAD

**Issue by jameskentTX** [pazznetwork/ngx-chat#20]
Error:
Cannot read property 'messages$' of undefined
    at ChatMessageListComponent.ngOnInit (pazznetwork-ngx-chat.js:3788)

From `app.component.html`:
`<ng-template #messagesComponentInformation>You need to be logged in and have contacts to see this component</ng-template>`

Description clearly states "You need to be logged in and have contacts to see this component".
But there is no check in the code if there are `contacts`.

And then in `ChatMessageListComponent` program is trying to subscribe to undefined variable
`this.messageSubscription = this.contact.messages$.subscribe(()...`
which throws error.

My solution:
`<ng-container *ngIf="(this.chatService.state$.getValue() === 'online') && ((this.chatService.contactsSubscribed$ | async).length > 0); else messagesComponentInformation">`

**Comment by trampi** [comment]
will investigate

**Comment by trampi** [comment]
Fixed in 0.9.0. I've used almost the same code as you.
