### ISSUE TITLE
Room name doesn't show any change after user join room

### ISSUE THREAD

**Issue by jameskentTX** [pazznetwork/ngx-chat#21]
Before join:
`polityka (0): polityka@conference.pc17.home`

After join:
`polityka (0): polityka@conference.pc17.home`

Should be:
`polityka (1): polityka@conference.pc17.home`

You have to click "List all rooms" to see updated names, but it should definitely update automatically. It's important to see in real time number of users in rooms.

**Comment by trampi** [comment]
Hi @jameskentTX, I will have a look at this, you're right, it should definitely live update!

**Comment by jameskentTX** [comment]
Thanks.

**Comment by CodeBast4rd** [comment]
Moving to strophe and observables will be fixed when to matching tests are written. 
https://github.com/pazznetwork/ngx-chat/tree/alternative-xmpp-adapter
