### ISSUE TITLE
error , cannot get the files 

### ISSUE THREAD

**Issue by harishreddy311** [pazznetwork/ngx-chat#26]
as per the given instructions i ran the application but application is not executing

**Comment by trampi** [comment]
Hi @harishreddy311,
do you get any error messages? Could post the output of the console?
Without further information I can not help.

**Comment by harishreddy311** [comment]
[image: issues.JPG]

hi after debugging the code this is what the above error i am getting help
us to resolve it

**Comment by trampi** [comment]
Hi. I do not see your image. Could you please attach it manually via the following link?
https://github.com/pazznetwork/ngx-chat/issues/26
