### ISSUE TITLE
Small configuration problem

### ISSUE THREAD

**Issue by jameskentTX** [pazznetwork/ngx-chat#29]
App 0.9.0 won't compile unless you add

```typescript
export * from './lib/components/chat-room-messages/chat-room-messages.component';
export * from './lib/components/chat-filedrop/file-drop.component';
export * from './lib/directives/links.directive';
```

in `public-api.ts`

In `multi-user-chat.component.html` vscode shows two errors (code compile and works anyway, so it is annoyance only, not an error):

1. line 11: `'ngx-chat-room-messages' is not a known element`
2. line 12: `'ngx-chat-message-input' is not a known element`

Full vscode error message from 1:

`'ngx-chat-room-messages' is not a known element:
1. If 'ngx-chat-room-messages' is an Angular component, then verify that it is part of this module.
2. If 'ngx-chat-room-messages' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
Can't bind to 'room' since it isn't a known property of 'ngx-chat-room-messages'.
1. If 'ngx-chat-room-messages' is an Angular component and it has 'room' input, then verify that it is part of this module.
2. If 'ngx-chat-room-messages' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.`

In `multi-user-chat-component.ts` vscode shows one error:

1. line 10: `Can't resolve all parameters for MultiUserChatComponent in /home/leszek/dev/tests/ngx-chat-angular9/src/app/multi-user-chat/multi-user-chat.component.ts: (?).`

It looks like components are exported, yet vscode complains.
I don't know how to correct it.

**Comment by trampi** [comment]
Hi @jameskentTX, I could confirm the problem, removed some previously public components from the api. I will publish a new release later this day which will fix this issue.

**Comment by jameskentTX** [comment]
Ok, thanks.
I have a question.
In `xmpp-chat-connection.service`, **sendIq** function,  you have following code:

```typescript
            if (!request.attrs.type) {
                throw new Error('iq stanza without type: ' + request.toString());
            }
```

But in `XEP-0045: Multi-User Chat` documentation IQ stanzas have no type attribute.
For example in https://xmpp.org/extensions/xep-0045.html#enter-managehistory :

Example 39. User Requests All History Since the Beginning of the Unix Era
```xml
<presence
    from='hag66@shakespeare.lit/pda'
    id='n13mt3l'
    to='coven@chat.shakespeare.lit/thirdwitch'>
  <x xmlns='http://jabber.org/protocol/muc'>
    <history since='1970-01-01T00:00:00Z'/>
  </x>
</presence>
```

If I try to send such stanza as above I get always an error.

**Comment by trampi** [comment]
@jameskentTX I've released 0.9.1, which should fix this

**Comment by trampi** [comment]
@jameskentTX: I see you did remove the question regarding the `sendIq`, have you solved it? You should use `send` instead in this case, if I remember your question correctly.

**Comment by jameskentTX** [comment]
Using `Send custom IQ packets` I can get archive MUC messages for selected room with `xmlns='urn:xmpp:mam:0'` and with `xmlns='urn:xmpp:mam:2'` too.

`xmlns='urn:xmpp:mam:0'` is from older specification: https://xmpp.org/extensions/attic/xep-0313-0.3.html

`xmlns='urn:xmpp:mam:2'` is from newer specification: https://xmpp.org/extensions/xep-0313.html

Older specification is working, newer too, but generates errors. I will look into it.
Thanks for 0.9.1 version, Trampi.

**Comment by trampi** [comment]
@jameskentTX Which errors do you get? Nice to hear that you get the messages. Which errors do you get?

**Comment by jameskentTX** [comment]
These errors are not important. To see them login into your app and then send two IQ stanzas to load messages from MUC room:

1.
```xml
<iq type='set' id='get_muc_chat_archives' to='polityka@conference.pc17.home'>
  <query xmlns='urn:xmpp:mam:0' queryid='f27' />
</iq>
```

2.
```xml
<iq type='set' id='get_muc_chat_archives1' to='polityka@conference.pc17.home'>
  <query xmlns='urn:xmpp:mam:2' queryid='f271' />
</iq>
```

Old specification (`urn:xmpp:mam:0`) is working without errors, newer (`urn:xmpp:mam:2`) is generating errors.
