### ISSUE TITLE
Send & recive messages

### ISSUE THREAD

**Issue by lolagardiel** [pazznetwork/ngx-chat#3]
Hi guys. I try to send and receive messages and I do not get it. Please, an example. Lola ;)

**Comment by lordoliver** [comment]
Besides the initialization as shown on readme you just have to call the chatservice like so:
`import { ChatService, ChatServiceToken } from '@pazznetwork/ngx-chat';

export class Whatever {

    constructor(@Inject(ChatServiceToken) public chatService: ChatService) {}

    public sendMessage() {
        const receiver = 'bla@blub.com'; // user bla on blub.com domain
        const merssage = 'Hi!';
        this.chatService.sendMessage(receiver, message);
                
    }

}`

**Comment by lolagardiel** [comment]
thank you very much, it seems that my problems were caused by openfire ssl self-signed and firefox. Does it work correctly in firefox? , I have several incidents always in firefox. Thanks guys )

**Comment by lordoliver** [comment]
Yes. It should work in Firefox. At least it does for me ;)

**Comment by trampi** [comment]
Hi @lolagardiel,
you could try to import your self-signed certificate into the firefox browser certificate store. It should work if the domain name matches the self signed certificates common name (CN).

I will close this issue and update the readme with information regarding certificates and using the API for sending messages. Feel free to reopen or to open another issue.  
 Cheers!
