### ISSUE TITLE
message-state.plugin.ts – Message States "bouncing" weird in UI

### ISSUE THREAD

**Issue by juliusdigital** [pazznetwork/ngx-chat#35]
Hello,

I've been having some issues with the message state plugin. 

The states switch back and forth in a weird way when the users "A" and "B" are in the active window - it looks like "something is wrong" in the user experience. The issue goes like this:

**Issue Description**

Contact A, sends a message to user B, both are in the active (open) window, now this happens:

1. Message is marked as SENT
2. Then, message is marked as SEEN
3. Then, message marked again as SENT
4. Finally, message marked as SEEN again.

I've found that there are several things going on in the "local" state fo the messages (the jidToMessageStateDate) and in the "server" the persistent "remote" state pubsub node... along with the notification message stanza being sent. Well...

... actually I happen to come with a "fix":

**BUG:**  

"MESSAGE STATE BOUNCING" From "sent" to "seen" to "sent" to "seen"

**SOLUTION:**

Compare local dates vs remote dates
Only update local dates if remote dates are greater
LOCAL DATE > REMOTE DATE ? YES = LEAVE DATE AS IS : NO = UPDATE WITH REMOTE ONE;
Do it for each date (sent, received, seen)

Notes: By "remote dates" I mean the ones that are retrieved from the pubsub.

**CODE**

_message-state.plugin.ts_
```typescript
// .
// . (more code before)
// .

private processPubSub(itemElement: Element[]) {
   const results = {} as JidToMessageStateDate;
   if (itemElement.length === 1) {
       for (const lastReadEntry of itemElement[0].getChild(wrapperNodeName).getChildren(nodeName)) {
           const {lastRecipientReceived, lastRecipientSeen, lastSent, jid} = lastReadEntry.attrs;
           const localState = this.getContactMessageState(jid);
           const remoteState = {
               lastSent: new Date(+lastSent || 0),
               lastRecipientReceived: new Date(+lastRecipientReceived || 0),
               lastRecipientSeen: new Date(+lastRecipientSeen || 0)
           };
           const isLocalSentNewer = localState.lastSent.getTime() > remoteState.lastSent.getTime();
           const isLocalReceivedNewer = localState.lastRecipientReceived.getTime() > remoteState.lastRecipientReceived.getTime();
           const isLocalSeenNewer = localState.lastRecipientSeen.getTime() > remoteState.lastRecipientSeen.getTime();

           results[jid] = {
               lastSent: isLocalSentNewer ?  localState.lastSent : remoteState.lastSent,
               lastRecipientReceived: isLocalReceivedNewer ?  localState.lastRecipientReceived : remoteState.lastRecipientReceived,
               lastRecipientSeen: isLocalSeenNewer ?  localState.lastRecipientSeen : remoteState.lastRecipientSeen,
           };
       }
   }
   this.jidToMessageStateDate = results;
}

// .
// . (more code before)
// .

public getContactMessageState(contactJid: string) {
   if (!this.jidToMessageStateDate[contactJid]) {
       this.jidToMessageStateDate[contactJid] = {
           lastRecipientReceived: new Date(0),
           lastRecipientSeen: new Date(0),
           lastSent: new Date(0),
       };
   }
   return this.jidToMessageStateDate[contactJid];
}

```

Now. That fixes the "bouncing", and gives better experience...
I haven't fully tested it yet, but it seems to work.

**BUT THERE'S ANOTHER ISSUE LEFT:**

**Message states not reported to offline users**

I'm working on it. You can reproduce the issue like this:

1. Contact A send a message to B (B is offline)
2. Contact A goes offline.
3. B connects online, just receive the messages (when he was offline),
    and then B again goes offline.
4. Contact A goes online, now he MUST see his message marked as RECEIVED, but it's just marked as "sent".
4.1. The same happens if contact B marked as "saw" the message... 

The issue is because the plugin right now is designed to work while the Contacts are ONLINE.

And the fix needs adjustments to the PubSub plugin for broader support of the XEP.
The idea is to allow contacts in the roster "read" the node from their peers (subscribe to the node) and get the status dates being persisted while online...

It needs to deal with `access_model` and many more things...

https://xmpp.org/extensions/xep-0060.html#accessmodels

Do you think of a better idea?

Thanks for the great work ;)

**Comment by trampi** [comment]
Hi @JulioFlores, thank you for this detailed report. I will have a detailed look tomorrow, but wanted you to know that I have seen it.

All the best!

**Comment by trampi** [comment]
Hi @JulioFlores, I've got good and bad news.

Lets start with the bad news first: I will be on vacation from 22.06. and be back in office starting at the 06.07. It is not very likely (but not impossible either...) that I will find time in the meantime to release a fixed version for the second issue (Message states not reported to offline users). Interestingly, when I implemented the feature, I am pretty confident it that it worked with offline contacts as well. Either it broke in the meantime, or it could be that your jabber server does not store the "silent read receipt messages" (`<message><message-state state="recipientReceived"></message-state></message>`'.  
To verify this, you could check if the `recipientReceived` stanza is being sent by contact B to contact A in step 3 after receiving the message from contact A. Should contact B send them and  contact A not receive them, than this is a jabber server issue. 
Which Jabber server are you connecting to?

The good news is that - if the bug is reproducible and not jabber server based - the "Message states not reported to offline users" bug should definitely be fixed.  

**A version containing a fix for the first issue based on your suggestions will be released not later than tomorrow.**

Feel free to provide a pull request for the second issue if it is urgent.

All the best,
Fabian / trampi

**Comment by trampi** [comment]
Hi!

I had lots of stuff to wrap up today and was not able to release today. I will release the fixed version tomorrow.

Sorry for the delay,
Fabian

**Comment by JulioFlores** [comment]
Hi Fabian,

I have some new discoveries and thoughts...

**First – We can't trust the machine Date() in JS as it is.**

I've found that if users are connected in different machines may have and will have different system clock. Thus, the timestamps are an issue to make compare operations.

Solution: We must have a way to get the Server date in UTC.

What I'm testing right now is to make an HTTP HEAD request in an angular service to the server to get the Server Date in a header, so this way all connected users rely on the same date time.

**Second – About offline message states**

Yeah! The xmpp server should store offline <messages> stanzas, even with empty body.

I sorted this out dealing with the xmpp server configuration. 

That works.

I'm using Ejabberd 20.04

-----

Though, I'm still dealing with more logic between de chat-message.component.ts and the message-state.plugin.ts to get the date comparision right ;)

I would suggest to don't post the proposed fix yet.

Thank you Fabian,
J

**Comment by trampi** [comment]
Hi @JulioFlores 

> **First – We can't trust the machine Date() in JS as it is.**
>
> I've found that if users are connected in different machines may have and will have different system clock. Thus, the timestamps are an issue to make compare operations.
> 
> Solution: We must have a way to get the Server date in UTC.

Yeah, makes complete sense. And [XEP-0202](https://xmpp.org/extensions/xep-0202.html) allows us to retrieve the time of the XMPP server for a shared understanding of "now"! Supported XMPP servers include:

* ejabberd
* prosody
* openfire

> What I'm testing right now is to make an HTTP HEAD request in an angular service to the server to get the Server Date in a header, so this way all connected users rely on the same date time.

I will provide a default implementation for a service utilizing XEP-0202 to get the shared "now". I will then compute the elapsed time via `performance.now()`. You will be able to provide your own implementation, e.g. should a XMPP server not implement XEP-0202. I will look into it now and will provide a status update later this evening.

> **Second – About offline message states**
> 
> I sorted this out dealing with the xmpp server configuration.

Nice to hear!

All the best,
Fabian

**Comment by trampi** [comment]
I pushed a commit on Branch ticket-35 which should improve the synchronization by implementing the algorithm outlined in my last message.
This is not tested extensively, so use with caution. In a quick test it behaved as expected.

I will not release a new version before the end of my vacation, but feel free to build upon it.

If you have further questions do not hesitate.

Regards,
Fabian

**Comment by JulioFlores** [comment]
Enjoy your vacation @trampi !

I’ll test it and comment back soon.

**Comment by trampi** [comment]
@JulioFlores Hi, any news from you?
Did you find time to test the proposed change? 😄

**Comment by JulioFlores** [comment]
> @JulioFlores Hi, any news from you?
> Did you find time to test the proposed change? 😄

Hi @trampi 

Sorry for the delay.

Yeah! I've tested and it seems to work more stable now.

I've made some adjustments to the `message.plugin.ts` where datetime is set.

**_message.plugin.ts_**

```ts
private async handleMessageStanza(messageStanza: MessageWithBodyStanza) {
       // ... more code
        const message = {
            body: messageStanza.getChildText('body'),
            direction: Direction.in,
            // datetime: new Date(), // Works semi OK
            datetime: new Date(await this.entityTimePlugin.getNow()),
            delayed: !!messageStanza.getChild('delay'),
        };
```

```ts
    async sendMessage(jid: string, body: string, thread?: MessageThread) {
        // ... more code
        const message: Message = {
            direction: Direction.out,
            body,
            // datetime: new Date(), // Works semi OK
            datetime: new Date(await this.entityTimePlugin.getNow()),
            delayed: false,
            thread: thread,
        };
```

I guess also the unread message plugin needs some adjustments ... ? I've not tried yet or seen any issues.

The code in the processPubSub in the plugin at https://github.com/pazznetwork/ngx-chat/issues/35#issue-639962663
fix the "bouncing issue", along with this code in the chat-message.component:

_**chat-message.component.ts**_

```ts
// enum definition
enum StateOrder {
    sending = 0,
    sent = 1,
    recipientReceived = 2,
    recipientSeen = 3
 }
```

```ts
    getMessageState() {

        if (this.messageStatePlugin && this.contact) {

            if (this.message.state === MessageState.RECIPIENT_SEEN) { return this.message.state; }

            const date = this.message.datetime;
            const states = this.messageStatePlugin.getContactMessageState(this.contact.jidBare.toString());

            const changedState = this.getStateForDate(date, states);
            const changedStateOrder = StateOrder[changedState];
            const currentStateOrder = this.message.state ? StateOrder[this.message.state] : StateOrder.sent;

            if ( currentStateOrder < changedStateOrder ) {
                this.message.state = changedState;
            }
            return this.message.state;
        }
    }
```

That "prevents" the message state go to a previous state, and only "forward":

SENDING -> SENT -> RECEIVED -> SEEN

**IMPORTANT:** To everyone reading this, the ejabberd machine MUST have the local time in UTC for this to work, so ejabberd can send the date in the "XEP-0202: Entity Time" with the universal time, and in the client (ngx-chat) you could convert that to a local timezone if you want. Also the mod MUST be enabled in ejabberd:

More info at: https://docs.ejabberd.im/archive/20_04/modules/#mod-time

### My To Do

I've created a way – with a custom API – to delete single messages from MAM in ejabberd doing a direct SQL query to the DB, I'm using a MySQL database config. I also delete the message in memory from the MessageStore and group by date in ngx-chat if the API returns OK to be reflected in the UI...

...sometimes in very rare ocassion I've seen that "I lose the message states", but that's another story... and I think out of the scope of the issue being discussed here ;)
