### ISSUE TITLE
How to fetch Openfire Additional User Properties ?

### ISSUE THREAD

**Issue by cankemik** [pazznetwork/ngx-chat#38]
Openfire has REST API feature that allows adding additional properties to user entry.

I'm guessing this feature is specific for Openfire only but are there any ways to retrieve this information in Contact metadata?

**Comment by trampi** [comment]
Hi @cankemik! You could subscribe to the `contacts$` Observable, request the properties for the user and add the data on demand.

The following code is used in a product of us and fetches the user information from another service and puts the data into metadata as well:

```typescript
this.chatService.contacts$
            .pipe(debounceTime(100))
            .subscribe(async contacts => {
                const contactsWithoutMetadata = contacts.filter(c => !c.metadata.profile)
                    .map(contact => ({contact, userId: this.getUserIdFromContact(contact)}))
                    .filter(c => c.userId !== null && c.userId !== '');
                const userIds = contactsWithoutMetadata.map(c => c.userId);
                const userProfiles = await this.userProfileService.findByIdArrayCached(userIds);
                const userIdToContactWithoutMetadata: Dictionary<DataEntry<UserProfile>> = keyBy(userProfiles, 'data.id');

                for (const contactWithoutMetadata of contactsWithoutMetadata) {
                    const userProfile = userIdToContactWithoutMetadata[contactWithoutMetadata.userId];
                    if (userProfile) {
                        this.setContactData(contactWithoutMetadata.contact, userProfile.data);
                    }
                }
            });
```

I have not had the time to look the REST API feature of Openfire up - do you know if it is based on a XEP? Maybe [XEP-0054 vcard-temp](https://xmpp.org/extensions/xep-0054.html)? Should it be an XEP, than it might make sense to include it into the core of ngx-chat.

**Comment by trampi** [comment]
Closed as I guess this is resolved. Do not hesitate to reopen or to open a new issue.
