### ISSUE TITLE
How do I get this to work?

### ISSUE THREAD

**Issue by hhokka** [pazznetwork/ngx-chat#39]
When I try to use ngx-chat, I use the following per instructions:

```
@NgModule({
    ...
    imports: [
        ...
        NgxChatModule.forRoot(),
        BrowserAnimationsModule, // alternatively NoopAnimationsModule 
    ],
    ...
})

```
Then it requires an import. I have guessed it to be `import { NgxChatModule } from @pazznetwork/ngx-chat`

After adding these lines my pages won't display at all.

**Comment by trampi** [comment]
Hi @hhokka,

do you have any erorrs in your browser console? You've correctly guessed the import 😄 
Are you using Angular 10?

**Comment by JulioFlores** [comment]
Hey @hhokka I would suggest you to get running the example project before diving in. Connect to your xmpp server and start some tests, afterwards carry on your own implementation by copying the imports and code you'd need.

**Comment by hhokka** [comment]
Hey,

I will do that. Thank you!

Regards,

Hans Hokka

ke 19. elok. 2020 klo 20.27 Julio R. Flores <notifications@github.com>
kirjoitti:

**Comment by trampi** [comment]
Closed as I guess this is resolved. Do not hesitate to reopen or to open a new issue.
