### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by sdomville** [pazznetwork/ngx-chat#43]
In the getting started part you say to  add the constructor code:
`  constructor(@Inject(ChatServiceToken) ChatService) {
    chatService.logIn({
        domain: 'ngx-chat.example',
        service: 'wss://ngx-chat.example:5280/websocket',
        password: 'password',
        username: 'someuser',
    });
}`

but that gives a TS error : Cannot find name 'chatService'. Did you mean 'ChatService'?ts(2552)

FYI

**Comment by trampi** [comment]
Hi @sdomville,
I have corrected the readme.
Thank you for reporting it!

All the best,
trampi
