### ISSUE TITLE
Compile errors in Angular app

### ISSUE THREAD

**Issue by sdomville** [pazznetwork/ngx-chat#44]
Hi - I installed via: 
`npm install --save @pazznetwork/ngx-chat @xmpp/client@~0.9.2`
and see these errors with ng build:

ERROR in node_modules/@pazznetwork/ngx-chat/lib/components/chat.component.d.ts(28,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@pazznetwork/ngx-chat/lib/core/contact.d.ts(27,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@pazznetwork/ngx-chat/lib/core/contact.d.ts(28,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@pazznetwork/ngx-chat/lib/core/contact.d.ts(29,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@pazznetwork/ngx-chat/lib/core/contact.d.ts(30,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@pazznetwork/ngx-chat/lib/core/contact.d.ts(31,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@pazznetwork/ngx-chat/lib/core/contact.d.ts(32,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@pazznetwork/ngx-chat/lib/services/adapters/xmpp/plugins/multi-user-chat.plugin.d.ts(35,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@pazznetwork/ngx-chat/lib/services/adapters/xmpp/plugins/multi-user-chat.plugin.d.ts(36,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@pazznetwork/ngx-chat/lib/services/adapters/xmpp/plugins/multi-user-chat.plugin.d.ts(37,9): error TS1086: An accessor cannot be declared in an ambient context.

**Comment by trampi** [comment]
Hi @sdomville,

could you give a bit more context, e.g. your package.json or a link to the repository of your project?
I can not reproduce your error locally. A newly created project with angular 10 works fine.

**Comment by trampi** [comment]
Hi @sdomville,

thank you for providing further information.

Unfortunately there is no support for Angular 7, we skipped it. You could try the angular 8 or angular 6 build. Only the current build line is supported actively.

> does "mutli-user" include group chat? That's what I really need! thanks!
Yes, group chat is supported (but not shown in the contact list on the right side of the page)

See https://pazznetwork.github.io/ngx-chat-ghpages/ at the bottom after signing in:

![Screen Recording 2020-09-24 at 14 31 44](https://user-images.githubusercontent.com/4292951/94146371-20500d00-fe74-11ea-9cf3-136ec2b2e5bd.gif)

**Comment by trampi** [comment]
Closed as I guess this is resolved. Do not hesitate to reopen or to open a new issue.
