### ISSUE TITLE
Error while trying to build lib

### ISSUE THREAD

**Issue by slimanLakhoua** [pazznetwork/ngx-chat#45]
Hello,

i have been trying lately to build the lib with the command provided in the readme file :
# build the library continuously
ng build @pazznetwork/ngx-chat --watch

but i still getting this error 

ERROR: projects/pazznetwork/ngx-chat/src/lib/services/adapters/xmpp/plugins/service-discovery.plugin.ts:145:9 - error TS2322: Type '{ identities: { [attrName: string]: any; }[]; features: any[]; jid: string; }' is not assignable to type 'Service'.
  Types of property 'identities' are incompatible.
    Type '{ [attrName: string]: any; }[]' is not assignable to type 'Identity[]'.
      Type '{ [attrName: string]: any; }' is missing the following properties from type 'Identity': category, type

145         return serviceInformation;
            ~~~~~~~~~~~~~~~~~~~~~~~~~~
projects/pazznetwork/ngx-chat/src/lib/services/adapters/xmpp/plugins/multi-user-chat.plugin.ts:336:9 - error TS2322: Type '{ [attrName: string]: any; }[]' is not assignable to type 'RoomSummary[]'.
  Type '{ [attrName: string]: any; }' is missing the following properties from type 'RoomSummary': jid, name

336         return roomElements.map(room => room.attrs);
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

An unhandled exception occurred: projects/pazznetwork/ngx-chat/src/lib/services/adapters/xmpp/plugins/service-discovery.plugin.ts:145:9 - error TS2322: Type '{ identities: { [attrName: string]: any; }[]; features: any[]; jid: string; }' is not assignable to type 'Service'.     
  Types of property 'identities' are incompatible.
    Type '{ [attrName: string]: any; }[]' is not assignable to type 'Identity[]'.
      Type '{ [attrName: string]: any; }' is missing the following properties from type 'Identity': category, type

145         return serviceInformation;
            ~~~~~~~~~~~~~~~~~~~~~~~~~~
projects/pazznetwork/ngx-chat/src/lib/services/adapters/xmpp/plugins/multi-user-chat.plugin.ts:336:9 - error TS2322: Type '{ [attrName: string]: any; }[]' is not assignable to type 'RoomSummary[]'.
  Type '{ [attrName: string]: any; }' is missing the following properties from type 'RoomSummary': jid, name

336         return roomElements.map(room => room.attrs);
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by trampi** [comment]
Hi! Can you show me your package.json? I suspect an outdated version of Typescript and / or an incompatible version of Angular.

**Comment by trampi** [comment]
Closed due to inactivity. Do not hesitate to reopen or to open a new issue.
