### ISSUE TITLE
Reagrding delete functionality

### ISSUE THREAD

**Issue by mounikamasetti** [pazznetwork/ngx-chat#47]
Hiow we can delete a message in this xmpp server by using pazznetwork ngx-chat

**Comment by trampi** [comment]
Hello @mounikamasetti,
ngx-chat has not implemented any functionality to delete messages. I do not know of any XMPP Standard (XEP) which allows that. If you could provide a link to a XEP, I would happily assist in implementing this feature.

**Comment by UsmanMajied17** [comment]
Hi trampi, i am going to implement pazznetwork ngx-chat very soon and reading this issue kinda disturbed me a bit. Let me reconfirm. Are you saying that messages cannot be deleted via xmpp or you have not implemented this feature yet? Thanks in advance.

**Comment by trampi** [comment]
Hi @UsmanMajied17,
deleting messages is not a part of the XMPP protocal as far as I am aware. ngx-chat can therefore not provide support for that.
There is an [abandoned XEP Standard Proposal](http://legastero.github.io/customxeps/extensions/message-delete.html), which has not been standardised. I am not aware of XMPP servers implementing this.

You could integrate a custom API for your XMPP server. Ejabberd for example does not allow to delete single messages. It however allows to delete all messages exchanged with a specific participant.

If you have further questions, do not hesitate. Note that I am on paternal leave and will take some time to reply.

**Comment by mounikamasetti** [comment]
Hai  @trampi 

Thanks for your suggesion I am also thinking in the same way that have to use implementing specific  custom url..

can u help me to develop file upload and download functionality in XMPP server

**Comment by trampi** [comment]
Hi! I am back from parental leave and will take a look at this at the beginning of the next week.

**Comment by trampi** [comment]
@mounikamasetti which XMPP server are you using?

**Comment by CodeBast4rd** [comment]
@mounikamasetti , @UsmanMajied17 

And delete of messages will be implemented following the standards when our own need for that justifies the effort.

For now Pull requests are welcome.
