### ISSUE TITLE
Feature-not-implemented loadCompleteHistory()

### ISSUE THREAD

**Issue by DevRichter** [pazznetwork/ngx-chat#48]
Hello,

i have a Problem with loading messages. As a XMPP-Server i use Openfire 4.6.0. When i load messages from a room (N to N Chat) i created and joined it works like a charm. All messages are saved and then loaded, even after i close my app. But when i try to load messages i send to a contact (1 to 1 Chat) just minutes ago, and reload my app, all messages are gone. 

So i tried to enable the Monitoring Service Plugin for Openfire, and it does archive all messages i send. When i then try to call the function loadCompleteHistory() i get the "feature-not-implemented" error. 

`core.js:4197 ERROR Error: Uncaught (in promise): <iq xmlns="jabber:client" type="error" id="1606997503937" to="alice@d715be968047/3cbsrauy6m"><error code="501" type="cancel"><feature-not-implemented xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error></iq>`

Heres how i call the functions in angular: 

`async loadAllArchivedMessages() {
    this.ngxChatService.loadCompleteHistory().then(async () => {
      await Promise.resolve();
    });`

`loadAllArchivedMessages() {
    this.chatService.loadAllArchivedMessages().then(() => console.log("hello"));
  }`

It does print the "hello", so the Promise does resolve, but the archived messages do not get loaded. Is there something that i do wrong, or is that a known issue?

**Comment by trampi** [comment]
Hi @DevRichter,

I'll have a look at this soon and will report back. The last time I've worked with Openfire I just had to enable the monitoring plugin. It sounds like a configuration issue.

**Comment by DevRichter** [comment]
Well, my colleague set up a docker container for the Openfire Server with a Postgres DB, which for some reason was falsly configured. My own configuration works fine now :) thank you for the quick answer, and awesome repository btw! Love the Documentation :)

**Comment by trampi** [comment]
Hi @DevRichter,
thank you for your feedback :-)

Should you have further questions or something not work as expected do not hesitate and open a new issue.

All the best,
trampi
