### ISSUE TITLE
HTTPUpload

### ISSUE THREAD

**Issue by DevRichter** [pazznetwork/ngx-chat#52]
Hey,

i have an Issue with uploading files to my openfire. I use the HTTPFileUploadPlugin, Openfire Http File Upload Plugin and <input type"file> from angular. I actually receive the correct object (imo):

`File {name: "example.txt", lastModified: 1602250514537, lastModifiedDate: Fri Oct 09 2020 15:35:14 GMT+0200 (Mitteleuropäische Sommerzeit), webkitRelativePath: "", size: 241, …}`

i pass that on to httpfileuploadplugin.upload(file), and i receive this http error:

`HttpErrorResponse {headers: HttpHeaders, status: 0, statusText: "Unknown Error", url: "http://localhost:7443/httpfileupload/1057a382-ca35-49d1-bb90-ef76b1617730/example.txt", ok: false, …}`

aswell as: 

`PUT http://localhost:7443/httpfileupload/1057a382-ca35-49d1-bb90-ef76b1617730/example.txt net::ERR_INVALID_HTTP_RESPONSE`

When i check my openfire logs i get the following messages (which indicate it working imo):

`2021.01.14 15:11:37 INFO [pool-37-thread-6]: nl.goodbytes.xmpp.xep0363.Component - Entity 'alice@localhost/9aie25a97n' tries to obtain slot.
2021.01.14 15:11:37 INFO [pool-37-thread-6]: nl.goodbytes.xmpp.xep0363.Component - Entity 'alice@localhost/9aie25a97n' obtained slot for 'example.txt' (241 bytes). PUT-URL: http://localhost:7443/httpfileupload/1057a382-ca35-49d1-bb90-ef76b1617730/example.txt GET-URL: http://localhost:7443/httpfileupload/1057a382-ca35-49d1-bb90-ef76b1617730/example.txt
`

Any advice on why these erros occur? 

Best regards
DevRichter

**Comment by trampi** [comment]
Hi! I am back from parental leave and will take a look at this at the beginning of the next week.

**Comment by trampi** [comment]
Interesting. Judging from the logs I would expect this to work. Will try to reproduce this in the near future, should not be too hard.

**Comment by CodeBast4rd** [comment]
Probably because of image headers on upload. New version will move the file upload away from any components to the service.

I am currently only able to test against ejabberd so without an reproduction environment I can not support other XMPP servers.
