### ISSUE TITLE
Angular 11?

### ISSUE THREAD

**Issue by duzenko** [pazznetwork/ngx-chat#54]
Is this library supposed to work with Angular 11? I get the following errors 
```

Error: node_modules/@pazznetwork/ngx-chat/lib/ngx-chat.module.d.ts:2:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

This likely means that the library (@pazznetwork/ngx-chat/lib/ngx-chat.module) which declares NgxChatModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

2 export declare class NgxChatModule {
                       ~~~~~~~~~~~~~
src/app/chat/components/chat/chat.component.html:3:1 - error NG8001: 'ngx-chat' is not a known element:
1. If 'ngx-chat' is an Angular component, then verify that it is part of this module.
2. If 'ngx-chat' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

```

**Comment by RafaelPuerta** [comment]
> Is this library supposed to work with Angular 11? I get the following errors
> 
> ```
> 
> Error: node_modules/@pazznetwork/ngx-chat/lib/ngx-chat.module.d.ts:2:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.
> 
> This likely means that the library (@pazznetwork/ngx-chat/lib/ngx-chat.module) which declares NgxChatModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
> 
> 2 export declare class NgxChatModule {
>                        ~~~~~~~~~~~~~
> src/app/chat/components/chat/chat.component.html:3:1 - error NG8001: 'ngx-chat' is not a known element:
> 1. If 'ngx-chat' is an Angular component, then verify that it is part of this module.
> 2. If 'ngx-chat' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
> ```

did you try angular 10?

**Comment by duzenko** [comment]
As a matter of fact it seems to work with 11, even though it gave incomprehensible errors at some point

**Comment by trampi** [comment]
reopened this issue to signalize everyone that it is not perfect at the moment but definitely is planned in the near future.

**Comment by trampi** [comment]
Just pushed Angular 11 compatible Version @pazznetwork/ngx-chat@0.11.0.
Should you have any issues or further questions do not hesitate to reopen this issue or open a new one.
