### ISSUE TITLE
How to login using authtoken - is it supported. I am using this within my application and my application auth mechanism is different so I don't want to put any password in Ng client code. Do let me know how to do that

### ISSUE THREAD

**Issue by bhumaha-ceo** [pazznetwork/ngx-chat#55]

**Comment by trampi** [comment]
Hi! I am back from parental leave and will take a look at this at the beginning of the next week. Could you provide more information about which server you're using, which auth method and so on?

**Comment by trampi** [comment]
Sorry, officially we only support password based authentication.
