### ISSUE TITLE
Tigase support?

### ISSUE THREAD

**Issue by duzenko** [pazznetwork/ngx-chat#56]
We tried this component with Tigase but it throws at least two different types of errors in the browser console
Can we have ngx-chat to support Tigase as well please?

**Comment by trampi** [comment]
Hi! I am back from parental leave and will take a look at this at the beginning of the next week. Support of tigase should be possible, as it seems compliant with XMPP RFCs / XEPs!

**Comment by trampi** [comment]
Hi! I will definitely come back to this, but got some other priorities at the moment.

**Comment by duzenko** [comment]
No problem, we won't need it any time soon
XMPP is too much hassle and we just implemented our own chat service instead
