### ISSUE TITLE
error while setting up ngx-chat

### ISSUE THREAD

**Issue by jesmayer99** [pazznetwork/ngx-chat#6]
```
ERROR in projects/pazznetwork/ngx-chat/src/lib/services/adapters/xmpp/plugins/service-discovery.plugin.ts(109,9): error TS2322: Type '{ identities: { [attrName: string]: any; }[]; features: any[]; jid: string; }' is not assignable to type 'Service'.
  Types of property 'identities' are incompatible.
    Type '{ [attrName: string]: any; }[]' is not assignable to type 'Identity[]'.
      Type '{ [attrName: string]: any; }' is not assignable to type 'Identity'.
        Property 'category' is missing in type '{ [attrName: string]: any; }'.
```

**Comment by trampi** [comment]
Hi @jesmayer99,

to help you, I need more information.

* Are you trying to compile the library?
* Which steps do you have taken to get that error message?
* Which commands have you executed?
* Which version of angular are you using?
* Could you provide steps to reproduce the error?

Note that ngx-chat needs @xmpp/client in version 0.3.0, install it via:
```
npm install --save @xmpp/client@~0.3.0
```

**Comment by jesmayer99** [comment]
> Hi @jesmayer99,
> 
> to help you, I need more information.
> 
> * Are you trying to compile the library?
> * Which steps do you have taken to get that error message?
> * Which commands have you executed?
> * Which version of angular are you using?
> * Could you provide steps to reproduce the error?
> 
> Note that ngx-chat needs @xmpp/client in version 0.3.0, install it via:
> 
> ```
> npm install --save @xmpp/client@~0.3.0
> ```

getting error after running serve using CLI- ng serve 
Angular-6.1.10
Angular CLI: 6.2.9
`ERROR in projects/pazznetwork/ngx-chat/src/lib/services/adapters/xmpp/plugins/service-discovery.plugin.ts(109,9): error TS2322: Type '{ identities: { [attrName: string]: any; }[]; features: any[]; jid: string; }' is not assignable to type 'Service'.
  Types of property 'identities' are incompatible.
    Type '{ [attrName: string]: any; }[]' is not assignable to type 'Identity[]'.
      Type '{ [attrName: string]: any; }' is not assignable to type 'Identity'.
        Property 'category' is missing in type '{ [attrName: string]: any; }'.`

**Comment by trampi** [comment]
How have you installed the library?

**Comment by jesmayer99** [comment]
> How have you installed the library?

git clone https://github.com/pazznetwork/ngx-chat.git 
sudo npm install

**Comment by trampi** [comment]
@jesmayer99 
I could not yet reproduce your problem here.
Could you run `rm -rf node_moduels` and run `npm install` without sudo? (by the way, running `sudo npm install` is in most cases not a good idea)

After that, you can start the local development build via:
`npm run start`

If that does not help, please post the output of:
```
node --version
npm --version
```

**Comment by jesmayer99** [comment]
> node --version
8.10.0
npm --version
3.5.2

after running rm -rf node_moduels and run npm install without sudo commands i am getting same error

**Comment by trampi** [comment]
Try a more recent node / npm version.
I could not get npm 3.5.2 to work here, 3.10 was not able to build the library, got errors like these:

```

BUILD ERROR
node_modules/rxjs/internal/types.d.ts(81,44): error TS1005: ';' expected.
node_modules/rxjs/internal/types.d.ts(81,74): error TS1005: ';' expected.
node_modules/rxjs/internal/types.d.ts(81,77): error TS1109: Expression expected.
node_modules/rxjs/internal/types.d.ts(82,52): error TS1005: ';' expected.
node_modules/rxjs/internal/types.d.ts(82,88): error TS1005: ';' expected.
node_modules/rxjs/internal/types.d.ts(82,92): error TS1109: Expression expected.

Error: node_modules/rxjs/internal/types.d.ts(81,44): error TS1005: ';' expected.
node_modules/rxjs/internal/types.d.ts(81,74): error TS1005: ';' expected.
node_modules/rxjs/internal/types.d.ts(81,77): error TS1109: Expression expected.
node_modules/rxjs/internal/types.d.ts(82,52): error TS1005: ';' expected.
node_modules/rxjs/internal/types.d.ts(82,88): error TS1005: ';' expected.
node_modules/rxjs/internal/types.d.ts(82,92): error TS1109: Expression expected.
```

**Comment by jesmayer99** [comment]
> Try a more recent node / npm version, I am using node v10.15.1 and npm 6.9.0.
> I could not get npm 3.5.2 to work here, 3.10 was not able to build the library, got errors like these:
> 
> ```
> 
> BUILD ERROR
> node_modules/rxjs/internal/types.d.ts(81,44): error TS1005: ';' expected.
> node_modules/rxjs/internal/types.d.ts(81,74): error TS1005: ';' expected.
> node_modules/rxjs/internal/types.d.ts(81,77): error TS1109: Expression expected.
> node_modules/rxjs/internal/types.d.ts(82,52): error TS1005: ';' expected.
> node_modules/rxjs/internal/types.d.ts(82,88): error TS1005: ';' expected.
> node_modules/rxjs/internal/types.d.ts(82,92): error TS1109: Expression expected.
> 
> Error: node_modules/rxjs/internal/types.d.ts(81,44): error TS1005: ';' expected.
> node_modules/rxjs/internal/types.d.ts(81,74): error TS1005: ';' expected.
> node_modules/rxjs/internal/types.d.ts(81,77): error TS1109: Expression expected.
> node_modules/rxjs/internal/types.d.ts(82,52): error TS1005: ';' expected.
> node_modules/rxjs/internal/types.d.ts(82,88): error TS1005: ';' expected.
> node_modules/rxjs/internal/types.d.ts(82,92): error TS1109: Expression expected.
> ```

After running on node v10.15.1 and npm 6.9.0 this typo occurs

ERROR in src/app/app.component.ts(6,5): error TS2305: Module '"/home/user/PycharmProjects/ngx-chat/src/app/ngx-chat-imports"' has no exported member 'ChatBackgroundNotificationService'.
src/app/app.component.ts(7,5): error TS2305: Module '"/home/user/PycharmProjects/ngx-chat/src/app/ngx-chat-imports"' has no exported member 'ChatListStateService'.
src/app/app.component.ts(8,5): error TS2305: Module '"/home/user/PycharmProjects/ngx-chat/src/app/ngx-chat-imports"' has no exported member 'ChatService'.
src/app/app.component.ts(9,5): error TS2305: Module '"/home/user/PycharmProjects/ngx-chat/src/app/ngx-chat-imports"' has no exported member 'ChatServiceToken'.
src/app/app.component.ts(10,5): error TS2305: Module '"/home/user/PycharmProjects/ngx-chat/src/app/ngx-chat-imports"' has no exported member 'Contact'.
src/app/app.component.ts(11,5): error TS2305: Module '"/home/user/PycharmProjects/ngx-chat/src/app/ngx-chat-imports"' has no exported member 'ContactFactoryService'.
src/app/app.component.ts(12,5): error TS2305: Module '"/home/user/PycharmProjects/ngx-chat/src/app/ngx-chat-imports"' has no exported member 'LogLevel'.
src/app/app.component.ts(13,5): error TS2305: Module '"/home/user/PycharmProjects/ngx-chat/src/app/ngx-chat-imports"' has no exported member 'LogService'.
src/app/app.component.ts(14,5): error TS2305: Module '"/home/user/PycharmProjects/ngx-chat/src/app/ngx-chat-imports"' has no exported member 'MultiUserChatPlugin'.
src/app/app.component.ts(15,5): error TS2305: Module '"/home/user/PycharmProjects/ngx-chat/src/app/ngx-chat-imports"' has no exported member 'RegistrationPlugin'.
src/app/app.component.ts(16,5): error TS2305: Module '"/home/user/PycharmProjects/ngx-chat/src/app/ngx-chat-imports"' has no exported member 'UnreadMessageCountPlugin'.
src/app/app.component.ts(17,5): error TS2305: Module '"/home/user/PycharmProjects/ngx-chat/src/app/ngx-chat-imports"' has no exported member 'XmppClientToken'.
src/app/app.module.ts(10,10): error TS2305: Module '"/home/user/PycharmProjects/ngx-chat/src/app/ngx-chat-imports"' has no exported member 'NgxChatModule'.
src/app/iq/iq.component.ts(3,10): error TS2305: Module '"/home/user/PycharmProjects/ngx-chat/src/app/ngx-chat-imports"' has no exported member 'ChatServiceToken'.
src/app/iq/iq.component.ts(3,28): error TS2305: Module '"/home/user/PycharmProjects/ngx-chat/src/app/ngx-chat-imports"' has no exported member 'XmppChatAdapter'.
src/app/multi-user-chat/multi-user-chat.component.ts(3,10): error TS2305: Module '"/home/user/PycharmProjects/ngx-chat/src/app/ngx-chat-imports"' has no exported member 'ChatService'.
src/app/multi-user-chat/multi-user-chat.component.ts(3,23): error TS2305: Module '"/home/user/PycharmProjects/ngx-chat/src/app/ngx-chat-imports"' has no exported member 'ChatServiceToken'.
src/app/multi-user-chat/multi-user-chat.component.ts(3,41): error TS2305: Module '"/home/user/PycharmProjects/ngx-chat/src/app/ngx-chat-imports"' has no exported member 'MultiUserChatPlugin'.
src/app/multi-user-chat/multi-user-chat.component.ts(3,62): error TS2305: Module '"/home/user/PycharmProjects/ngx-chat/src/app/ngx-chat-imports"' has no exported member 'Room'.
src/app/ngx-chat-imports.ts(2,15): error TS2307: Cannot find module '@pazznetwork/ngx-chat'.
src/app/send-stanza/send-stanza.component.ts(3,10): error TS2305: Module '"/home/user/PycharmProjects/ngx-chat/src/app/ngx-chat-imports"' has no exported member 'ChatServiceToken'.
src/app/send-stanza/send-stanza.component.ts(3,28): error TS2305: Module '"/home/user/PycharmProjects/ngx-chat/src/app/ngx-chat-imports"' has no exported member 'XmppChatAdapter'.

**Comment by trampi** [comment]
Hi,
thats better!

Try `npm start` instead of `ng serve`.
`npm start` builds the library and runs the demo application, while `ng serve` only runs the demo application (and requires an already built library, which you do not have at the moment).

**Comment by jesmayer99** [comment]
> instead

thanks it's solve my issue

**Comment by trampi** [comment]
You're welcome, do not hesitate if you have further questions :-)
