### ISSUE TITLE
ejabberd configuration

### ISSUE THREAD

**Issue by jameskentTX** [pazznetwork/ngx-chat#7]
Could you please add your ejabberd.yml to documentation?
I'm trying - with partial success - to view your ngx-chat, but MUC doesn't work (individual chat works very well). Pidgin client see rooms on my ejabberd server, but your app doesn't.
I guess maybe if I update my ejabberd server configuration according to your guidelines, MUC will work.

I have ejabberd 19.02.131, compiled from source.

**Update**
I made some tests and here are my observations:

After I join room (polityka@conference.pc17.home/test) there are unknown stanzas reported:

ChatService: unknown stanza <=presence xmlns="jabber:client" xml:lang="en" to="test@pc17.home/121400852556687662463106" from="polityka@conference.pc17.home/leszek"=><=c xmlns="http://jabber.org/protocol/caps" node="http://pidgin.im/" hash="sha-1" ver="AcN1/PEN8nq7AHD+9jpxMV4U6YM=" ext="voice-v1 camera-v1 video-v1"/=><=x xmlns="vcard-temp:x:update"/=><=x xmlns="http://jabber.org/protocol/muc#user"=><=item role="participant" affiliation="none"/=><=/x=><=priority=>1<=/priority=><=/presence=>

where polityka@conference.pc17.home/leszek is pidgin user

Interesting that roster sees room, but when I try to send message prom pidgin your app shows error:
ChatService: error handling stanza in  MultiUserChatPlugin Error: no room with given jid found: polityka@conference.pc17.home

ChatService: unknown stanza <= (message xmlns="jabber:client" xml:lang="en" to="test@pc17.home/121400852556687662463106" from="polityka@conference.pc17.home/leszek" type="groupchat" id="purplefeb22741")(archived by="polityka@conference.pc17.home" id="1559202866878904" xmlns="urn:xmpp:mam:tmp"/)(stanza-id by="polityka@conference.pc17.home" id="1559202866878904" xmlns="urn:xmpp:sid:0"/)(body)bbb(/body)(/message)

Looks like ejabberd doesn't stricly follow xep-0045 specifications and that's why your app doesn't recognize important presence stanzas:

ChatService: unknown stanza <= (presence xmlns="jabber:client" xml:lang="en" to="test@pc17.home/121400852556687662463106" from="polityka@conference.pc17.home/test")(x xmlns="vcard-temp:x:update"/)(x xmlns="http://jabber.org/protocol/muc#user")(item jid="test@pc17.home/121400852556687662463106" role="participant" affiliation="none"/)(status code="110"/)(/x)(/presence)

and 

ChatService: unknown stanza <= (message xmlns="jabber:client" to="test@pc17.home/121400852556687662463106" from="polityka@conference.pc17.home" type="groupchat")(subject/)(/message)

**Update2**
Could you please check joinRoomInternal function of MultiUserChatPlugin?
Are you sure it should work?
const roomJoinedPromise = new Promise<Stanza>(resolve => this.roomJoinPromises[occupantJid.toString()] = resolve);

**Comment by shejinbasheer01** [comment]
How did you fetch the rooms? for me the $rooms is always empty

**Comment by jameskentTX** [comment]
> How did you fetch the rooms? for me the $rooms is always empty

I didn't. 
ngx-chat doesn't see ejabberd rooms, that's the problem I'm trying to solve

**Comment by trampi** [comment]
Hello @jameskentTX,

if it works with other clients, you probably won't need ejabberd.yml tweaking ;-)
[Here is a video, demonstrating how to join a MUC in the demo app.](https://owncloud.trampusch.info/index.php/s/RnstBFdEWreg7A5)

> Pidgin client see rooms on my ejabberd server

Currently, ngx-chat does not implement the API to fetch the room list from the server.
However, according to the spec that should be pretty straightforward to implement. I will add it and publish it today.

Just as another information, we also do not support vcard-temp (XEP-0054) for e.g. loading contact names via XMPP yet.
The product were using ngx-chat in retrieves the contact names via business logic.
I will add support for vcard-temp in the (near?) future.

Another point is that the multi user chat rooms are not yet displayed in the roster list.
If you would like to see the currently joined XMPP rooms there, I could implement that if you request it.
At the moment, you can use the following code to render group messages:

```html
<ngx-chat-room-messages [room]="room"></ngx-chat-room-messages>
<ngx-chat-message-input [room]="selectedRoom"></ngx-chat-message-input>
```

with room being a `Room` instance.

> After I join room (polityka@conference.pc17.home/test) there are unknown stanzas reported:

I will have a look at that, but unknown stanzas usually do not cause trouble.
With ejabberd 18.09 it works, I will test it with 19.02 and report back

> Could you please check joinRoomInternal function of MultiUserChatPlugin?
> Are you sure it should work?
> const roomJoinedPromise = new Promise(resolve => this.roomJoinPromises[occupantJid.toString()] = resolve);

Yes. The promise gets resolved in [`handleRoomPresenceStanza`](https://github.com/pazznetwork/ngx-chat/blob/a44973f33d2abfad2b92b856894f4dde4adee877/projects/pazznetwork/ngx-chat/src/lib/services/adapters/xmpp/plugins/multi-user-chat.plugin.ts#L184-L192).

If you have further bugs / questions / feature requests do not hesitate ask!

**Comment by jameskentTX** [comment]
Thanks Trampi for your reply. But without changes in ejabberd.yml your app didn't work for me.
I had to remove mod_vcard module, because this module changes stanza structure, push "x" in second position in stanza children. And your function isRoomPresenceStanza is analyzing child with index 0.

Your code is awesome. I'm learning a lot from it.
but this:
const roomJoinedPromise = new Promise(resolve => this.roomJoinPromises[occupantJid.toString()] = resolve);
I can't understand how it works. It's mind-bending :D

**Comment by trampi** [comment]
> Thanks Trampi for your reply. But without changes in ejabberd.yml your app didn't work for me.
>  I had to remove mod_vcard module, because this module changes stanza structure, push "x" in second position in stanza children. And your function isRoomPresenceStanza is analyzing child with index 0.

Hah, thank you, that makes sense and is definitely a bug. I'll fix it today.

>  const roomJoinedPromise = new Promise(resolve => this.roomJoinPromises[occupantJid.toString()] = resolve);
I can't understand how it works. It's mind-bending :D

I'll try to explain it :-)  
The intention behind that code is, to wait until the server acknowledged the room join. Let me make a simple example to explain it:
```typescript
const promise = new Promise(resolve => this.promiseToResolveLater = resolve);
await promise;
console.log('promise finished!');
```

Now, someone can resolve the promise somewhere else by calling:
`this.promiseToResolveLater()`. After that, 'promise finished' gets logged to the console. Who and when the promise gets resolved does not matter.

In the ngx-chat case, we want to wait for the server to acknowledge our room join.
This will happen later in the future, we have to wait for a acknowledgement from the server that we have joined the room.
`handleRoomPresenceStanza` gets called from `handleStanza` (which is called every time we receive a message from the server) and will resolve the promise, signalling that we are now in the room.

> I'm learning a lot from it.
Glad to hear :-) You're always welcome if you have any questions.

**Comment by jameskentTX** [comment]
Mind-bending and so simple! :D
Now I understand, at last! :) Thank you very much for your excellent explanation.
