### ISSUE TITLE
unknown stanza  error on creationRoom

### ISSUE THREAD

**Issue by camiloestrada69** [pazznetwork/ngx-chat#76]
![image](https://user-images.githubusercontent.com/57564474/130698157-ac7bb388-86e5-4de0-bbba-7d9f2cf5c026.png)
log.service.ts:26 ChatService: unknown stanza<=<presence from="camilo.estrada@muclight.localhost/NuevaSala" to="camilo.estrada@localhost/74737302ae6259681629-843463-719554" type="error" xmlns="jabber:client"><error code="400" type="modify"><bad-request xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error></presence>

**Comment by CodeBast4rd** [comment]
The unknown stanze Problem is a known one I am currently working at. Our Plugins to implement fully the necessary XEP'S.

Pull Requests are welcome.
