### ISSUE TITLE
Customize Chat Adapter

### ISSUE THREAD

**Issue by juergen83** [pazznetwork/ngx-chat#83]
Hi, can I add custom logic to the xmpp-chat-adapter class? Or I have to clone/install (npm install <git-URL>) the whole repository for customizing this module?

I tried the following solution to inherit the adapter class:
`export class CustomXmppChatAdapter extends XmppChatAdapter {
constructor(
        public chatConnectionService: XmppChatConnectionService,
        private logSrv: LogService,
        private contactFactorySrv: ContactFactoryService
    ) {
        super(chatConnectionService, logSrv, contactFactorySrv);
    }
}
`

But at the end the service 'ChatService' uses the old adapter class.

**Comment by CodeBast4rd** [comment]
`@Inject(TokenName) private newChatService` in your constructor to use the provided service in your parent module `{provide: ChatServiceToken, useValue: newChatService},`.
