### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by jameskentTX** [pazznetwork/ngx-chat#9]
First message to chat room generates well known `ExpressionChangedAfterItHasBeenCheckedError` error:

```
ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'ngIf: [object Object]'. Current value: 'ngIf: true'.
    at viewDebugError (core.js:17857)
    at expressionChangedAfterItHasBeenCheckedError (core.js:17845)
    at checkBindingNoChanges (core.js:18045)
    at checkNoChangesNodeInline (core.js:27623)
    at checkNoChangesNode (core.js:27612)
    at debugCheckNoChangesNode (core.js:28216)
    at debugCheckDirectivesFn (core.js:28144)
    at Object.eval [as updateDirectives] (AppComponent.html:77)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js:28133)
    at checkNoChangesView (core.js:27511)
```

Hey Trampi, I will suggest some changes now, but keep in mind I'm not a professional programmer, so look at my suggestions very carefully, as they may harm your app in places I don't see.

You can eliminate `ExpressionChangedAfterItHasBeenCheckedError` error if you subscribe to contacts.
I made these changes:

app.component.ts

```
import { Component, Inject, OnDestroy } from '@angular/core';
...
    public contacts$: Observable<Contact[]> = this.chatService.contactsSubscribed$;
    public contacts: Contact[];
    public subscription;
...
        chatBackgroundNotificationService.enable();
        this.subscription = this.contacts$.subscribe(contacts => {
            this.contacts = contacts;
        });
...
    onToggleContactList() {
        if (this.contacts$ === this.chatService.contactsSubscribed$) {
            this.contacts$ = of([
                this.contactFactory.createContact('user@host', 'user1'),
                this.contactFactory.createContact('user2@host', 'user2'),
            ]);
        } else {
            this.contacts$ = this.chatService.contactsSubscribed$;
        }
    }
...
    ngOnDestroy() {
        this.subscription.unsubscribe();
    }
```

app.component.html:
```
        <ng-container *ngIf="contacts.length > 0; else messagesComponentInformation">
            <ngx-chat-message-list [contact]="contacts[0]"
                                   [showAvatars]="true"></ngx-chat-message-list>
            <ngx-chat-message-input [contact]="contacts[0]"></ngx-chat-message-input>
        </ng-container>
...
<ngx-chat rosterState="shown" [contacts]="contacts$"></ngx-chat>
```

I have upgraded your app to Angular 8 and is working after some minor changes.
I removed @angular/http from dependencies.

```
  "dependencies": {
    "@angular/animations": "~8.0.0",
    "@angular/cdk": "~8.0.0",
    "@angular/common": "~8.0.0",
    "@angular/compiler": "~8.0.0",
    "@angular/core": "~8.0.0",
    "@angular/forms": "~8.0.0",
    "@angular/platform-browser": "~8.0.0",
    "@angular/platform-browser-dynamic": "~8.0.0",
    "@angular/router": "~8.0.0",
    "@types/ltx": "^2.6.3",
    "@xmpp/client": "^0.3.0",
    "core-js": "^2.5.4",
    "rxjs": "~6.4.0",
    **"tslib": "^1.9.3",** <-- moved from devDependencies
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.800.1",
    "@angular-devkit/build-ng-packagr": "^0.800.1",
    "@angular/cli": "~8.0.1",
    "@angular/compiler-cli": "~8.0.0",
    "@angular/language-service": "~8.0.0",
    "@commitlint/cli": "^7.2.1",
    "@commitlint/config-angular": "^7.1.2",
    "@compodoc/compodoc": "^1.1.3",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^10.0.0",
    "codelyzer": "^5.0.0",
    "concat-files": "^0.1.1",
    "conventional-changelog-cli": "^2.0.12",
    "coveralls": "^3.0.2",
    "debug": "^4.1.1",
    "glob": "^7.1.2",
    "husky": "^1.1.3",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "ng-packagr": "^3.0.6",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tsickle": "^0.29.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3",
    "webpack-bundle-analyzer": "^2.13.1"
  },
```

I made these changes in your code (specification of @ViewChild was changed)
https://blog.ninja-squad.com/2019/05/29/what-is-new-angular-8.0/

1. projects/pazznetwork/ngx-chat/src/lib/components/chat-room-messages/chat-room-messages.component.ts
@ViewChild('messageArea', { static: false })
2. projects/pazznetwork/ngx-chat/src/lib/components/chat-window/chat-window.component.ts
@ViewChild(ChatMessageInputComponent, { static: false })
3. projects/pazznetwork/ngx-chat/src/lib/components/chat-message-list/chat-message-list.component.ts
@ViewChild('messageArea', { static: false })
4. projects/pazznetwork/ngx-chat/src/lib/services/adapters/xmpp/plugins/service-discovery.plugin.ts

**This is not a good change, but bad practice !!**
```
export interface Service {
    jid: string;
    identities: any; // Identity[];
    features: string[];
}
```

After these changes your app is working without errors I can notice, but my tests were very limited. I simply logged in, sent few messages, subscribe to room etc. So errors may surface in other places.

Warning:
I have upgraded devDependencies testing libraries, so they are now the same as when you generate new app in Angular 8 with: ng new test1
So your tests won't work probably without some upgrade. 

My node version is 10.16.0 => "@types/node": "^10.0.0"

Node 12 is good too, app is working without errors, after upgrade "@types/node" to newest 12.0.4 version.

**Comment by trampi** [comment]
Hi @jameskentTX,
awesome, thank you for your work!

I will integrate your proposed changes until the next release.

**Comment by jameskentTX** [comment]
It's nothing. Everybody can make such easy and rude changes. But only you can... update @xmpp/client to newest version :D This library is almost 2 years old and has a lot of dependencies which were updated as well.

**Comment by trampi** [comment]
Hey @jameskentTX,
I will do that, but I do not know when. I did investigate into updating @xmpp/client but want to also minimize the bundle size of ngx-chat. Because I could not selectively include what i need starting with 0.5.0 I postponed the update of @xmpp/client. I do not know about real disadvantages in ngx-chat because of the older @xmpp/client.

If you need a newer version of @xmpp/client let me know.

**Comment by jameskentTX** [comment]
I didn't know about bundle size issue. In such circumstances there is probably no need to update ngx-chat. I don't need newer version of @xmpp/client, I've just thought that it's would be worth to update to newer version, because of many updates in @xmpp/client and it's dependencies.

I noticed that there is no possibility to lazy load ngx-chat. Am I correct?
I could use lazy loading of ngx-chat but I'm also good with your app in current state, so please do not do it on my account :) It's just a question.

**Comment by jameskentTX** [comment]
Hi Trampi!
I had to correct small detail in package.json and loosen types to successfully compile ngx-chat:

1. package.json
"typescript": "~3.4.5",
2. service-discovery.plugin.ts
identities: any[]; // Identity[];
3. multi-user-chat.plugin.ts
export interface RoomSummary {
    jid?: string;
    name?: string;
}

**Comment by trampi** [comment]
Hi @jameskentTX,

> I noticed that there is no possibility to lazy load ngx-chat. Am I correct?

Yeah, thats true. We had no use-case where lazy-loading ngx-chat is necessary et.

>1. package.json
>"typescript": "~3.4.5",

Can you provide the output why the typescript currently used does not work?

>2. service-discovery.plugin.ts
>identities: any[]; // Identity[];

Can you provide the error of the compiler here as well? I do not see where the types might not fit.

>3. multi-user-chat.plugin.ts
>export interface RoomSummary {
>    jid?: string;
>    name?: string;
>}

Same as above 😄 

> I also had runtime error:
> Cannot read property 'length' of null
Do you provide a custom contact source for `<ngx-chat></ngx-chat>`?


As the original issue is solved, I close it. Feel free to either answer here or open new issues!

**Comment by jameskentTX** [comment]
Just clone ngx-chat, load dependencies with yarn install and you'll get these errors.
If you use npm there is runtime error only, if you try to log in.
